name: Unit Tests

on:
  push:
    branches:
      - develop

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Unit Tests
        run: flutter test